### ISSUE TITLE
Check why information is lost in the db after `mark-me-as-infected`.

### ISSUE THREAD

**Issue by niconomaa** [niconomaa/contactbook#8]

**Comment by lheilmann** [comment]
@niconomaa Kann ich hier helfen? 🌝

**Comment by niconomaa** [comment]
Maaybee :) haben gerade mak versucht, ob die mark me as infected mutation geht -- tut sie :) nur hat die node danach einige felder nicht mehr...

**Comment by lheilmann** [comment]
Welche felder fehlen?

**Comment by niconomaa** [comment]
nevermind :)
